# Generated by Django 5.1.4 on 2025-02-03 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=120)),
                ('fm_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=120)),
                ('fm_id', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.club')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.player')),
            ],
        ),
    ]
