# Generated by Django 5.1.4 on 2025-03-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=120)),
                ('logo_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nationality_name', models.CharField(max_length=120)),
                ('flag_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=120)),
                ('max_transfer_value', models.CharField(max_length=20, null=True)),
                ('player_photo_url', models.CharField(max_length=200, null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.player')),
            ],
        ),
    ]
