# Generated by Django 5.1.4 on 2025-02-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.CreateModel(
            name='PlayerTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.team')),
            ],
        ),
    ]
