# Generated by Django 5.1.4 on 2025-02-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0002_remove_player_teams_playerteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerteams',
            old_name='team',
            new_name='team_id',
        ),
    ]
