# Generated by Django 5.1.7 on 2025-03-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0002_user_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
