# Generated by Django 5.1.7 on 2025-03-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0003_remove_game_id_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.IntegerField(default=1),
        ),
    ]
