# Generated by Django 5.1.7 on 2025-03-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0004_alter_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.user')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_players', to='footballnerds.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballnerds.player')),
            ],
        ),
    ]
