# Generated by Django 5.1.7 on 2025-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0005_game_is_active_alter_user_username_gameplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_turn',
            new_name='turn_number',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
