# Generated by Django 5.1.7 on 2025-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0006_rename_current_turn_game_turn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='turn_number',
            field=models.IntegerField(default=1),
        ),
    ]
