# Generated by Django 5.1.7 on 2025-03-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballnerds', '0007_gameplayer_turn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footballnerds.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footballnerds.nationality'),
        ),
    ]
